os: osx
osx_image: xcode11.2
language: node_js
node_js: '12'
before_script:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
script:
  - yarn lint
  - yarn type-check
  - yarn dist
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DqivEfiJvupVSSkXonbIEmHaXsuSmf4sO5ZVvkC1uTVvWISks/Xa0i8VeVIsIBm2r+p9fKNPa8PNKyikbGFF8X0pSh7rTmHIbtMuc22G9xMBvZ8tTYNtIwhMNhydh3nA1cYYN4AkL/1Iz3Aowa8SzrTy2JRBkMiLTKKvf/sNbRoJccdF35LUsiM9D8CsKAHRZ1HWhFOjxVmHTxhrcVMZ8iSKMMJlHqfRHKhxS8pcizF3NPckw3xhMs5vDpFStqd6kZytBWTgaaJ6mTk27Wwxi8YUPlOTddx4AESYZoNSYeksYCUIaJo4en7cmlA/9h3c6y0XIjv9lFvZCsFBBrBmV9dy0gqcggMe/oHee6mwdltyU37cES2t1yvB+GK31KscxS2S6VT2UIvtQt4vo445YzySSqA8M79g9JTeEnnH62D9hynWJDnVC7V8grRWFDUJ1Ta1/FwXTbVTeFw6MPRY3fdZKmxlhkOokNdeyI/PFrGv3X6OhzXWKVz763iC9NBEAREOWxZYiFtGgb/DwPIxW/sV0wgOPO1KhSl2bgWbjYDbjV350IDDUP3o052fNyAu4ZtqIYLBUwZs4z93HwcH00NIhIx3dzVEdAergAaMyGbnbO/we8tTOMgOjVvKEHt2JSYxErgGq1g5gGW8ERi9RXa4YBrNll2Byp5iVXioSME=
  file_glob: true
  file: dist/*
  on:
    tags: true
